name: Generate mihomo Rules

on:
  schedule:
    # Запускать в 2:00 UTC каждый день (5 утра по МСК)
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Download and install Mihomo
        run: |
          # Скачиваем последнюю версию mihomo для linux
          # ИСПРАВЛЕННАЯ СТРОКА НИЖЕ (добавлены символы)
          LATEST_URL=$(curl -sL https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.assets | select(.name | test("mihomo-linux-amd64-.*\\.gz$")) |.browser_download_url')
          curl -sL -o mihomo.gz "$LATEST_URL"
          gunzip mihomo.gz
          chmod +x mihomo
          # Перемещаем исполняемый файл в системный каталог, чтобы он был доступен везде
          sudo mv mihomo /usr/local/bin/

      - name: Run build script
        run: bash./build.sh

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto-update mihomo rule sets"
          file_pattern: dist/*.mrs
