name: Generate mihomo Rules

on:
  schedule:
    # Запускать в 2:00 UTC каждый день (5 утра по МСК)
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and install Mihomo
        run: |
          echo "⬇️ Скачиваем .deb пакет Mihomo..."
          curl -L -o mihomo.deb \
            https://github.com/MetaCubeX/mihomo/releases/download/v1.19.9/mihomo-linux-amd64-v1.19.9.deb
        
          echo "📦 Устанавливаем..."
          sudo apt-get update
          sudo apt-get install -y ./mihomo.deb

      # --- КЛЮЧЕВОЙ ШАГ ДЛЯ ИСПРАВЛЕНИЯ ОШИБКИ ---
      # Этот шаг удаляет символы \r (CR) и делает скрипт исполняемым.
      - name: Fix line endings and make script executable
        run: |
          sed -i 's/\r$//' ./build.sh
          chmod +x ./build.sh

      - name: Run build script
        # Запускаем скрипт напрямую, так как мы сделали его исполняемым
        run: ./build.sh

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto-update mihomo rule sets"
          file_pattern: dist/*.mrs
